name: Salesforce Build Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment : Production
    # Use salesforcedx container
    container:
      image: salesforce/salesforcedx:latest-full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name : Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      - name : Create folder for later use
        run : mkdir akshayguptadev && cd akshayguptadev
      
      - name : Copy jwt token
        run : echo "${{ secrets.JWT_KEY }}" > jwt.key
      
      - name : Authorize with the org
        run : sfdx auth:jwt:grant --clientid ${{ secrets.CLIENT_KEY }} --jwtkeyfile jwt.key --username ${{ secrets.USER_NAME }}
      
      - name : Run validation
        run: sfdx force:source:deploy -c -p force-app
