name: Salesforce Full Deployment Job

# Controls when the workflow will run
on:
  # Triggers the workflow when pull request is merged but only for the "master" branch
  pull_request:
    types: [ closed ]
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Full-Deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment : Production
    # Use salesforcedx container
    container:
      image: salesforce/salesforcedx:latest-full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Copy jwt token
        run: echo "${{ secrets.JWT_KEY }}" > jwt.key
      
      - name: Authorize with the org
        run: sfdx auth:jwt:grant --clientid ${{ secrets.CLIENT_KEY }} --jwtkeyfile jwt.key --username ${{ secrets.USER_NAME }}
      
      - name: Set configuration
        run: sfdx config:set defaultusername=${{ secrets.USER_NAME }}

      - name : Running Deployment
        run : sfdx force:source:deploy -p force-app