name: Salesforce Full Validation Job

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Full-Validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: Production
    # Use salesforcedx container
    container:
      image: salesforce/salesforcedx:latest-full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      
      - name: Copy jwt token
        run: echo "${{ secrets.JWT_KEY }}" > jwt.key
      
      - name: Authorize with the org
        run: sfdx auth:jwt:grant --clientid ${{ secrets.CLIENT_KEY }} --jwtkeyfile jwt.key --username ${{ secrets.USER_NAME }}
      
      - name: Set configuration
        run: sfdx config:set defaultusername=${{ secrets.USER_NAME }}

      - name: Install code analysis plugin
        run: sfdx plugins:install @salesforce/sfdx-scanner && sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run code scan
        run: sfdx scanner:run --target "force-app/main/default" --engine "eslint-lwc,retire-js,cpd,pmd" --verbose

      - name: Running validation and test classes
        run: sfdx force:source:deploy -c -p force-app --testlevel RunLocalTests
